version: "3.8"
services:
  app:
    container_name: topeducation
    image: topeducation
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/TopEducation
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postre
    depends_on:
      - db

  db:
    container_name: topeducationbd
    image: postgres:latest
    environment:
      POSTGRES_DB: TopEducation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postre
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql